name: ci

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/*.yml'

jobs:
  stonedb:
    name: DBMS Tests (StoneDB)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check disk space
        run: df . -H
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Check disk space
        run: df . -H
      - name: Set up StoneDB
        run: |
          docker pull stoneatom/stonedb
      - name: Check disk space
        run: df . -H